config/routes.rb
Rails.application.routes.draw do
  resources :parent_details do
    collection do
      post:import
    end 
  end
  resources :user_details
  root 'user_details#index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/parent_detail.rb
class ParentDetail < ApplicationRecord
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_detail.rb
class UserDetail < ApplicationRecord
    mount_uploader :photo, PhotoUploader # Tells rails to use this uploader for this model.   
    validates :Name, presence: true # Make sure the owner's name is present.   

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/parent_details_controller.rb
class ParentDetailsController < ApplicationController
  before_action :set_parent_detail, only: %i[ show edit update destroy ]
  def import
    return redirect_to request.referer, notice: 'No file added' if params[:file].nil?
    return redirect_to request.referer, notice: 'Only CSV files allowed' unless params[:file].content_type == 'text/csv'

    CsvImportService.new.call(params[:file])

    redirect_to parent_details_path, notice: 'imported successfully'
  end

  # GET /parent_details or /parent_details.json
  def index
    @parent_details = ParentDetail.all
  end

  # GET /parent_details/1 or /parent_details/1.json
  def show
  end

  # GET /parent_details/new
  def new
    @parent_detail = ParentDetail.new
  end

  # GET /parent_details/1/edit
  def edit
  end

  # POST /parent_details or /parent_details.json
  def create
    @parent_detail = ParentDetail.new(parent_detail_params)

    respond_to do |format|
      if @parent_detail.save
        format.html { redirect_to parent_detail_url(@parent_detail), notice: "Parent detail was successfully created." }
        format.json { render :show, status: :created, location: @parent_detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @parent_detail.errors, status: :unprocessable_entity }
      end
    end
  end



  # PATCH/PUT /parent_details/1 or /parent_details/1.json
  def update
    respond_to do |format|
      if @parent_detail.update(parent_detail_params)
        format.html { redirect_to parent_detail_url(@parent_detail), notice: "Parent detail was successfully updated." }
        format.json { render :show, status: :ok, location: @parent_detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @parent_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parent_details/1 or /parent_details/1.json
  def destroy
    @parent_detail.destroy

    respond_to do |format|
      format.html { redirect_to parent_details_url, notice: "Parent detail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parent_detail
      @parent_detail = ParentDetail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def parent_detail_params
      params.require(:parent_detail).permit(:first_name, :last_name, :Address, :phone_number, :email)
    end


  end

app/controllers/user_details_controller.rb
class UserDetailsController < ApplicationController
  before_action :set_user_detail, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /user_details or /user_details.json
  def index
    @user_details = UserDetail.all
  end

  # GET /user_details/1 or /user_details/1.json
  def show
  end

  # GET /user_details/new
  def new
    @user_detail = UserDetail.new
  end

  # GET /user_details/1/edit
  def edit
  end

  # POST /user_details or /user_details.json
  def create
    
    
    @user_detail = UserDetail.new(user_detail_params)

    respond_to do |format|
      if @user_detail.save
        format.html { redirect_to user_detail_url(@user_detail), notice: "User detail was successfully created." }
        format.json { render :show, status: :created, location: @user_detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_details/1 or /user_details/1.json
  def update
    respond_to do |format|
      if @user_detail.update(user_detail_params)
        format.html { redirect_to user_detail_url(@user_detail), notice: "User detail was successfully updated." }
        format.json { render :show, status: :ok, location: @user_detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_details/1 or /user_details/1.json
  def destroy
    @user_detail.destroy

    respond_to do |format|
      format.html { redirect_to user_details_url, notice: "User detail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_detail
      @user_detail = UserDetail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_detail_params
      params.require(:user_detail).permit(:Name, :User_id, :photo, :Address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parent_details_helper.rb
module ParentDetailsHelper
end

app/helpers/user_details_helper.rb
module UserDetailsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Uploadapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

  </head>

  <body>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

    <%= yield %>
  </body>
</html>

app/views/parent_details/_form.html.erb
<%= form_with(model: parent_detail, local: true) do |form| %>
  <% if parent_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(parent_detail.errors.count, "error") %> prohibited this parent_detail from being saved:</h2>

      <ul>
        <% parent_detail.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :Address %>
    <%= form.text_field :Address %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
for inserting data from csv file:
<%=form_tag import_parent_details_path,method: :post,multipart: true do%>
<div><%=file_field_tag :file,accept:".csv"%></div>
<div>
<%=submit_tag 'Import'%>
</div>
<%end%>

app/views/parent_details/edit.html.erb
<h1>Editing Parent Detail</h1>

<%= render 'form', parent_detail: @parent_detail %>

<%= link_to 'Show', @parent_detail %> |
<%= link_to 'Back', parent_details_path %>

app/views/parent_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Parent Details</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Address</th>
      <th>Phone number</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parent_details.each do |parent_detail| %>
      <tr>
        <td><%= parent_detail.first_name %></td>
        <td><%= parent_detail.last_name %></td>
        <td><%= parent_detail.Address %></td>
        <td><%= parent_detail.phone_number %></td>
        <td><%= parent_detail.email %></td>
        <td><%= link_to 'Show', parent_detail %></td>
        <td><%= link_to 'Edit', edit_parent_detail_path(parent_detail) %></td>
        <td><%= link_to 'Destroy', parent_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parent Detail', new_parent_detail_path %>

app/views/parent_details/new.html.erb
<h1>New Parent Detail</h1>

<%= render 'form', parent_detail: @parent_detail %>



<%= link_to 'Back', parent_details_path %>

app/views/parent_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User detail:</strong>
  <%= @parent_detail.User_detail_id %>
</p>

<p>
  <strong>First name:</strong>
  <%= @parent_detail.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @parent_detail.last_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @parent_detail.Address %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @parent_detail.phone_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @parent_detail.email %>
</p>

<%= link_to 'Edit', edit_parent_detail_path(@parent_detail) %> |
<%= link_to 'Back', parent_details_path %>

app/views/user_details/_form.html.erb
<%= form_with(model: user_detail, local: true) do |form| %>
  <% if user_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_detail.errors.count, "error") %> prohibited this user_detail from being saved:</h2>

      <ul>
        <% user_detail.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Name %>
    <%= form.text_field :Name %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>

  <div class="field">
    <%= form.label :Address %>
    <%= form.text_field :Address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_details/edit.html.erb
<h1>Editing User Detail</h1>

<%= render 'form', user_detail: @user_detail %>

<%= link_to 'Show', @user_detail %> |
<%= link_to 'Back', user_details_path %>

app/views/user_details/index.html.erb
<p id="notice"><%= notice %></p>

 <h1>User Details</h1>

<div class="table-responsive{-sm|-md|-lg|-xl|-xxl}">
<table class="table border-secondary caption-top">
  <caption>List of users</caption>

   <thead class="table-light">
     <tr>
       <th>Name</th>
       <th>User</th>
       <th>Photo</th>
       <th>Address</th>
       <th colspan="4">Action</th>
     </tr>
   </thead>

   <tbody>
     <% @user_details.each do |user_detail| %>
       <tr>
         <td><%= user_detail.Name %></td>
         <td><%= user_detail.User_id %></td>
         <td><img src="<%=user_detail.photo%>" width="90" height="90"></td>
         <td><%= user_detail.Address %></td>
         <td><%= link_to "showimage", user_detail.photo_url,class:'btn btn-outline-success btn-sm'%></td>   
         <td><%= link_to 'Show', user_detail, class:'btn btn-outline-success btn-sm' %></td>
         <td><%= link_to 'Edit', edit_user_detail_path(user_detail),class:'btn btn-outline-success btn-sm'%></td>
         <td><%= link_to 'Destroy', user_detail,class:'btn btn-outline-success btn-sm',method: :delete, data: { confirm: 'Are you sure?' } %></td>
       </tr>
     <% end %>
   </tbody>
 </table>
 </div>

 <br>

 <%= link_to 'New User Detail', new_user_detail_path %><br>
 <%=link_to 'Log Out', destroy_user_session_path, method: :delete%><br>
 <%= link_to "edit profile", edit_user_registration_path%><br>
 <%=link_to "Parent Detail", parent_details_path %><br> 

app/views/user_details/new.html.erb
<h1>New User Detail</h1>

<%= render 'form', user_detail: @user_detail %>

<%= link_to 'Back', user_details_path %>

app/views/user_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user_detail.Name %>
</p>

<p>
  <strong>User:</strong>
  <%= @user_detail.User_id %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @user_detail.photo %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user_detail.Address %>
</p>

<%= link_to 'Edit', edit_user_detail_path(@user_detail) %> |
<%= link_to 'Back', user_details_path %>